version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  
  [[blocks.segments]]
    type = 'battery'
    style = 'plain'
    background_templates = [
      "{{if eq \"Charging\" .State.String}}{{end}}",
      "{{if eq \"Discharging\" .State.String}}{{end}}",
      "{{if eq \"Full\" .State.String}}{{end}}"
    ]
    template = " {{ if not .Error }}{{ if eq .State.String \"Charging\" }}{{ .Icon }}{{ end }}{{ if eq .State.String \"Discharging\" }}{{ .Icon }}{{ end }}{{ if eq .State.String \"Full\" }}{{ .Icon }}{{ end }}{{ if lt .Percentage 20 }}{{ .Percentage }}%{{ if lt .Percentage 10 }}!{{ end }}{{ end }}{{ end }} "

    [blocks.segments.properties]
    discharging_icon = "󱟤 "
    charging_icon = "󱟦 "
    charged_icon = "󱟢 "

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 10000


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'green'
  background = 'transparent'
  template = '❯❯ '
